/* Generated By:JavaCC: Do not edit this line. EagleMLParserConstants.java */
package eagleml.frontEnd;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EagleMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int BOOLEAN = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int TRUE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int THEN = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int DEF = 16;
  /** RegularExpression Id. */
  int VAL = 17;
  /** RegularExpression Id. */
  int LET = 18;
  /** RegularExpression Id. */
  int IN = 19;
  /** RegularExpression Id. */
  int END = 20;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 21;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 22;
  /** RegularExpression Id. */
  int HEX_LITERAL = 23;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 24;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 25;
  /** RegularExpression Id. */
  int EXPONENT = 26;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 27;
  /** RegularExpression Id. */
  int STRING_LITERAL = 28;
  /** RegularExpression Id. */
  int IDENTIFIER = 29;
  /** RegularExpression Id. */
  int LETTER = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int LPAREN = 32;
  /** RegularExpression Id. */
  int RPAREN = 33;
  /** RegularExpression Id. */
  int LBRACE = 34;
  /** RegularExpression Id. */
  int RBRACE = 35;
  /** RegularExpression Id. */
  int LBRACKET = 36;
  /** RegularExpression Id. */
  int RBRACKET = 37;
  /** RegularExpression Id. */
  int SEMICOLON = 38;
  /** RegularExpression Id. */
  int COMMA = 39;
  /** RegularExpression Id. */
  int DOT = 40;
  /** RegularExpression Id. */
  int ASSIGN = 41;
  /** RegularExpression Id. */
  int GT = 42;
  /** RegularExpression Id. */
  int LT = 43;
  /** RegularExpression Id. */
  int BANG = 44;
  /** RegularExpression Id. */
  int TILDE = 45;
  /** RegularExpression Id. */
  int QUESTION_MARK = 46;
  /** RegularExpression Id. */
  int COLON = 47;
  /** RegularExpression Id. */
  int EQ = 48;
  /** RegularExpression Id. */
  int NEQ = 49;
  /** RegularExpression Id. */
  int LEQ = 50;
  /** RegularExpression Id. */
  int GEQ = 51;
  /** RegularExpression Id. */
  int OR = 52;
  /** RegularExpression Id. */
  int AND = 53;
  /** RegularExpression Id. */
  int PLUS = 54;
  /** RegularExpression Id. */
  int MINUS = 55;
  /** RegularExpression Id. */
  int TIMES = 56;
  /** RegularExpression Id. */
  int DIVIDE = 57;
  /** RegularExpression Id. */
  int BIT_AND = 58;
  /** RegularExpression Id. */
  int BIT_OR = 59;
  /** RegularExpression Id. */
  int XOR = 60;
  /** RegularExpression Id. */
  int REM = 61;
  /** RegularExpression Id. */
  int LSHIFT = 62;
  /** RegularExpression Id. */
  int RIGHT_SIGNED_SHIFT = 63;
  /** RegularExpression Id. */
  int RIGHT_UNSIGNED_SHIFT = 64;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"bool\"",
    "\"int\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"def\"",
    "\"val\"",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
  };

}
